sudo: required
language: java
install: true
jdk:
  - oraclejdk7
env:
  global:
    - XDG_RUNTIME_DIR="/tmp"

# GUI is required for eclipse testing
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
script: 
 - mvn clean install

cache:
  directories:
    - '$HOME/.m2/repository'
    
after_failure: 
- cat /home/travis/build/bmaggi/eclipse-tycho-archetype/target/test-classes/projects/test1/project/myArtifactId/myArtifactId.test/target/work/data/.metadata/.log
